### ISSUE TITLE
Windows build problems

### ISSUE THREAD

**Issue by sectortechadmin** [fzwoch/obs-golang-plugin#4]
It looks like Go is unable to link to libobs? I have tdm-gcc installed, as well as `obs-studio` and 'pkgconfiglite' installed via Chocolatey.

```
$ go build -buildmode=c-shared -o plugin.dll
# pkg-config --cflags  -- libobs
Package libobs was not found in the pkg-config search path.
Perhaps you should add the directory containing `libobs.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libobs' found
pkg-config: exit status 1
```

**Comment by fzwoch** [comment]
That seems you dont have thw pkgconfig file for libobs. More like a build setup issue.

**Comment by sectortechadmin** [comment]
> That seems you dont have thw pkgconfig file for libobs. More like a build setup issue.

If it's not too much to ask, can you add instructions on setting up the build environment from scratch? I've gotten both the Rust and CPP plugin templates to build so far.

**Comment by fzwoch** [comment]
Actually, yes. There are 3 different platforms, each with 2 different architectures, making it 6. Then there are countless possibilities to build each. I for one do not even build on Windows. And everything gets outdated over the course of 3 months. I'm not going to maintain that.

**Comment by sectortechadmin** [comment]
Even just seeing one proper setup can help as a starting place for a future CI/CD effort, which we will probably need to make for our plugin. If you have at least one Windows environment that you could outline deployment for, I'd appreciate that a ton, and make a PR with some GH Actions.

**Comment by fzwoch** [comment]
I really have no idea for Windows as using external libraries has always been a pain. I would recommend to use MSYS2's Mingw target. It should come with a 'decent' Linux like environment including pkg-config. If they have a decent libobs in there I cannot tell. Else check the docs of https://pkg.go.dev/cmd/cgo. You will need to give options where headers and the libobs is to be found instead of using pkg-config - only you can say where they are on your system.
